const sections = {
  HOME: "home",
  DISCORD: "discord",
  TOKEN_DASHBOARD: "token-dashboard",
  FEATURED_APPLICATION: "featured-application",
  GITHUB: "github",
  MAILING_LIST: "mailing-list",
  DESCRIPTION: "description",
  TEAM: "team",
  DEFINITION: "definition",
  ADVISORS: "advisors",
  SUPPORTERS: "supporters",
  home: {
    HOME: "home",
    FEATURE_CAROUSEL: "feature-carousel",
    SUMMARY_GRID: "summary-grid",
    MINILOGO_GRID: "minilogo-grid",
    KEEP_BLOG: "keep-blog",
    EXCHANGES: "exchanges",
    LOGO_WALL: "logo-wall",
    CONTACT: "contact",
  },
  build: {
    HOME: "home-build",
    FEATURE_CARD: "build-feature-card",
    COMMUNITY_SHOWCASE: "community-showcase",
    SUMMARY_GRID: "build-summary-grid",
    CONTACT: "contact",
  },
  stake: {
    HOME: "home-stake",
    FEATURE_CARD: "stake-feature-card",
    SUMMARY_GRID: "stake- summary-grid",
    BANNER_BUSINESS_TEAM: "banner-business-team",
    BLOG_POST: "blog-post",
    BANNER: "banner",
  },
  faq: {
    HOME: "home-faq",
    QUESTIONS: "questions",
    CONTACT: "contact",
  },
  press: {
    HOME: "home-press",
    MINILOGO_GRID: "press-minilogo-grid",
    KEEP_BLOG: "keep-blog",
    LATEST_POST: "latest-post",
  },
  team: {
    HOME: "home-team",
    CEO_INFO: "ceo-info",
    BANNER: "team-banner",
    TEAM_GALLERY: "team-gallery",
    ADVISOR_GALLERY: "advisor-gallery",
  },
  info: {
    HOME: "home-info",
    FEATURE: "feature",
    FEATURE_CARD: "info-feature-card",
    TBTC_SHOWCASE: "tbtc-showcase",
    SUMMARY_GRID: "info-summary-grid",
    CONTACT: "contact",
  },
}

const routes = {
  CALIFORNIA_PRIVACY: "/california-privacy-notice",
  MAIN: "/",
  PLAYING_FOR_KEEPS_TERMS: "/playing-for-keeps-terms",
  PRESS: "/press",
  BUILD: "/build",
  STAKE: "/stake",
  FAQ: "/faq",
  TEAM: "/team",
  INFO: "/info",
  PRIVACY: "/privacy-policy",
  TERMS: "/terms-of-use",
}

export { routes, sections }
